In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from math import sqrt
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import scipy as sp

In [8]:
cars_df = pd.read_excel("cars.xls")
cars_df.head()

Model   MPG  Cylinders  Displacement  Horsepower  \
0  chevrolet chevelle malibu  18.0          8         307.0         130   
1          buick skylark 320  15.0          8         350.0         165   
2         plymouth satellite  18.0          8         318.0         150   
3              amc rebel sst  16.0          8         304.0         150   
4                ford torino  17.0          8         302.0         140   

   Weight  Acceleration  Year Origin  
0    3504          12.0    70     US  
1    3693          11.5    70     US  
2    3436          11.0    70     US  
3    3433          12.0    70     US  
4    3449          10.5    70     US

In [9]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Model         392 non-null    object 
 1   MPG           392 non-null    float64
 2   Cylinders     392 non-null    int64  
 3   Displacement  392 non-null    float64
 4   Horsepower    392 non-null    int64  
 5   Weight        392 non-null    int64  
 6   Acceleration  392 non-null    float64
 7   Year          392 non-null    int64  
 8   Origin        392 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 27.7+ KB


In [10]:
y = cars_df.MPG
x = cars_df.Horsepower

In [11]:
x_train,x_test,y_train,y_test = train_test_split(pd.DataFrame(x),y,test_size=0.3,random_state=42)

In [12]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [13]:
y_prediction = regressor.predict(x_test)
y_prediction

array([29.60673686, 21.95467101, 31.10388018, 29.44038761, 26.77879949,
       28.60864132, 12.80546185, 28.60864132, 25.28165617, 32.93372202,
        9.47847669, 23.11911582, 15.30070071, 28.60864132, 18.96038438,
       26.44610097, 25.28165617, 28.60864132, 27.77689503, 26.44610097,
       25.28165617, 32.43467424, 29.77308612, 19.45943215, 29.93943538,
       26.11340245, 26.61245023, 23.61816359, 33.43276979, 28.44229206,
       16.96419329, 26.11340245, 20.29117844, 28.77499058, 16.132447  ,
       29.93943538, 17.79593957, 27.77689503, 17.79593957,  5.31974525,
       19.45943215, 28.60864132, 28.77499058, 28.10959355, 16.46514551,
        5.31974525, 24.44990988, 29.60673686, 29.10768909, 29.44038761,
       15.63339922, 25.28165617, 26.11340245, 26.44610097, 22.45371879,
       22.7864173 , 22.7864173 , 24.44990988, 25.28165617, 25.28165617,
        3.65625268, 26.11340245, 21.95467101, 26.44610097, 25.28165617,
       27.61054577, 26.44610097, 29.44038761, 22.7864173 ,  8.14

In [14]:
y_prediction = regressor.predict(x_test)
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

4.955413560049774


In [18]:
y=cars_df.MPG
x=cars_df[['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration', 'Year']]
x_train, x_test, y_train, y_test= train_test_split(x,y)

In [23]:
scaler=MinMaxScaler()
x_train_sc=pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
x_test_sc=pd.DataFrame(scaler.transform(x_test),columns=x_test.columns)
regressor = LinearRegression()
regressor.fit(x_train_sc, y_train)

LinearRegression()

In [25]:
y_prediction=regressor.predict(x_test_sc)
RMSE=sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

3.775252578166907


In [26]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
x=np.arange(10).reshape(-1,1)
y=np.array([0,0,0,0,1,1,1,1,1,1])

In [32]:
model=LogisticRegression(solver='liblinear', random_state=0)

In [33]:
model.fit(x,y)

LogisticRegression(random_state=0, solver='liblinear')

In [34]:
model=LogisticRegression(solver='liblinear', random_state=0).fit(x,y)

In [35]:
model.predict_proba(x)

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [36]:
model.predict(x)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [37]:
model.score(x,y)

0.9

In [38]:
confusion_matrix(y, model.predict(x))

array([[3, 1],
       [0, 6]], dtype=int64)

In [42]:
model=LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [44]:
model.score(x,y)

1.0

In [45]:
confusion_matrix(y, model.predict(x))

array([[4, 0],
       [0, 6]], dtype=int64)

In [52]:
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs

In [53]:
x, y = make_blobs(n_samples=1000, centers=2, random_state=0, cluster_std=0.60)

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.3)

In [55]:
model = SVC(kernel='linear', C=1E10)
model.fit(x,y)

SVC(C=10000000000.0, kernel='linear')

In [57]:
accuracy_score(y_test, model.predict(x_test))

1.0

In [59]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer

In [66]:
x_train, x_test, y_train, y_test = train_test_split(cancer.data, cancer.target, random=0)
svc = SVC()
svc.fit(x_train, y_train)
print('Accuracy on training set: {:.2f}'.format(svc.score(x_train, y_train)))
print('Accuracy on test set: {:.2f}'.format(svc.score(x_test, y_test)))

AttributeError: 'function' object has no attribute 'data'

In [65]:
min_on_training = x_train.min(axis=0)
range_on_training= (x_train - min_on_training).max(axis=0)
x_train_scaled = (x_train - min_on_training) / range_on_training
x_test_scaled = (x_test - min_on_training) / range_on_training
svc = SVC()
svc.fit(x_train_scaled, y_train)
print('Accuracy on training set: {:.3f}'.format(svc.score(x_train_scaled, y_train)))
scv.score(x_train_scaled, y_train)
print('Accuracy on test set: {:.3f}'.format(svc(x_test_scaled, y_test)))

Accuracy on training set: 1.000


NameError: name 'scv' is not defined